version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sregh10161Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: LowerFSPackage
  gitServerName: src_shared_GH_Arti_auto
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
